### ISSUE TITLE
Checklist of existing features to rewire back in

### ISSUE THREAD

**Issue by fedarko** [marbl/MetagenomeScope#181]
For most of these, I can reuse most of the code -- the challenge will just be hooking things up properly.

A lot of these can also be extended a lot now that the tool is refactored, too -- e.g. for "search for nodes", we now can implement not only in-this-component searching but also searching over all components. I guess I should probs focus on regaining existing functionality and then, from there, extending stuff.

### Python script

- [ ] Read and use user-specified bubble files (`-ub` option)
- [ ] Read and use user-specified "misc. pattern" files (`-up` option)
- [ ] SPQR tree decomposition (`-spqr` option)
  - Due to all of the challenges involved in getting this specifically supported, and since the hierarchical decomp. is now implemented, I may leave this in the "classic MetagenomeScope" release for the time being
- [ ] Output structural pattern information (`-sp` option)
- [ ] Output DOT files for every component / pattern (just contain the graph topology) (`-pg` option)
- [ ] Output XDOT files for every component / pattern (contain the actual laid-out coordinates and everything as determined by Graphviz) (`-px` option)
- [ ] Output DOT files for every component without using backfilling (patterns are represented as clusters) (`-nbdf` option)
  - I wasn't sure if Graphviz supports arbitrarily nesting clusters, but apparently [it does](https://github.com/ReneNyffenegger/about-Graphviz/blob/master/examples/nested-clusters.dot), so this should still work with hierarchical pattern stuff
  - This will be useful for the paper, for a figure showing the difference backfilling makes on layout linearity
- [ ] Output DOT files for every component without structural pattern information embedded (`-npdf` option)
  - Again, will be useful for the paper.

### JS interface

- [ ] Search for nodes
- [ ] Collapse/uncollapse all patterns
- [ ] Straighten currently drawn edges
- [ ] Filter edges by weight (this one should really be refactored into a more general histogram method, e.g. for node coverage / length)
- Color nodes:
  - [ ] By a given numeric field (length, any extra things like coverage, GC content, ...)
  - (Previously, we only supported coloring by specifically-named fields (e.g. "GC content"). Ideally, we should support coloring by any of the data fields labeled as `extra_node_attrs`, provided at least two unique numeric values exist for the selected field.
- [ ] View scaffolds
- [ ] Manual finishing
  - [ ] AGP export
  - [ ] CSV export
- [ ] Export graph view
  - [ ] Button in the top-right of the graph
  - [ ] Buttons at the bottom of the menu
- [ ] Test layouts?
  - (I might not add this back.)
