### ISSUE TITLE
Identifying cyclic bubbles?

### ISSUE THREAD

**Issue by fedarko** [marbl/MetagenomeScope#241]
To clarify, we still disallow cycles (including self-loop edges) _within_ bubbles. However, if there exists an edge (or edges, since we now allow multigraphs) from the end node to the start node, then we could still detect this as a bubble.

A very simple example of this is shown in the following drawing:

![original_b56cf619-8552-4d18-8060-4d7e35a1ea19_PXL_20230411_052021824](https://user-images.githubusercontent.com/4177727/231063515-a00fe659-6ceb-406d-b58e-f5fd8dc6c9e4.jpg)

How should we represent bubbles like this?

## Option 1

![PXL_20230411_050643165](https://user-images.githubusercontent.com/4177727/231063578-074806c4-8b4d-4654-b66f-cc87c0a03d8c.jpg)

- The entire structure is contained within a single "bubble" pattern.
  - **Pros:**
    - simple representation
    - hey, at least this still "catches" this bubble
  - **Cons:**
    - doesn't visually distinguish this bubble from other, non-cyclic bubbles
    - breaks the general "rule" of split boundary nodes that left nodes only carry incoming connections and that right nodes only carry outgoing connections (so, this would require special-casing)...? (Although: I guess we will have to do something similar for cyclic chains, so this isn't that big of a deal.)
    - we don't catch these sorts of bubbles when finding bulges / 3-node bubbles / super-bubbles, so this would be inconsistent unless we'd adjust these other algorithms. (Counterpoint: It should be fairly easy to adjust these other algorithms -- with the exception of the super-bubble one, maybe -- to allow cyclic bubbles.)

## Option 2

![PXL_20230411_051019531](https://user-images.githubusercontent.com/4177727/231063685-dac071af-d638-4991-8515-8d1907431e45.jpg)

- We contain the entirety of the structure (except for the back-edge) within a single "bubble" pattern, and then we route the end node's right split back to the starting node's left split.
  - **Pros:**
    - No need for special-casing on which boundary nodes get which edges
    - We could then detect this structure (node -> pattern -> node -> back to the original node) as a cyclic chain, which has the nice property of encoding this as a bubble within a cycle
  - **Cons:**
    - In the case where there are other pattern(s) on the boundary of this cyclic bubble (see this image: ![PXL_20230411_053031143](https://user-images.githubusercontent.com/4177727/231065163-c00ddc90-ec6b-4e59-8571-629ff47da16e.jpg)), these other patterns will not be detected (at least, if they're bubbles) because their ending / starting "nodes" will have interfering connections (the back-edge) that will break pattern detection. So, if this cyclic bubble occurs in a chain of bubbles, then we wouldn't detect its neighbors as bubbles. This is not a problem for option 1.
    - It isn't clear to me how we'd handle "splitting" the boundary nodes of a newly-created pattern if this pattern's boundary nodes are both already split. This happens because we are creating a pattern that is a complete superset of another pattern; this isn't what the auto-boundary-splitting was intended for.
    - This is still inconsistent with the bulge/3-node/super algorithms, although as discussed in option 1 this is not a big con.

## Option 3

Just disallow cyclic bubbles, at least for now.

## Verdict

At first I was just writing this up to justify why I was going to go with option 3 (disallowing cyclic bubbles), but after reviewing everything I don't think there is much harm in allowing cyclic bubbles with option 1. We can always toggle this behavior / add a CLI option if people really don't like it, but I think this functionality should be helpful.

## TODOs

- [x] allow cyclic bulges
- [x] allow cyclic 3-node bubbles
- [x] allow cyclic superbubbles
- [x] test cyclic bulges
- [x] test cyclic 3-node bubbles
- [x] test cyclic superbubbles
- [ ] test hierarchical decomposition on the cyclic-bubble-in-a-chain-of-bubbles case (this graph is already created in `test_cyclic_bubble_in_bubble_chain()`, but i want to verify that the resulting decomposition stuff actually works as intended)
- [ ] think about the isolated cyclic bubble thing described below -- consider disallowing cyclic bubbles and frayed ropes (not as much work as it sounds, since I merged most of the bubble finding functions together), or write up something in the documentation about this, or modify the code to detect these corner cases and force a consistent result
- [ ] Maaaaybe add a new pattern type for "cyclic bubbles" that we classify these as. (Analogous to how there is a chain pattern type, and a "cyclic chain" pattern type.) I'm hesitant about this, though (don't wanna overwhelm the user with different colors); maybe make a new issue to think about this.

**Comment by fedarko** [comment]
Coming back to this: a silly property (that I should have thought of earlier) is that these kinds of "cyclic bubbles" (when they are an isolated component of the graph) technically contain a chain from the end to the start node. The figure below shows that, depending on whether you identify the bubble or the chain first, the resulting decomposition looks different:

![image](https://user-images.githubusercontent.com/4177727/232680812-6969214d-2d35-44a5-92fb-ea3c81745cc4.png)

(I didn't draw it out in the figure, but the final step of the right side would be merging the chain and bubble into a cyclic chain. Also, the L and R subscripts indicate node splitting: see #167)

Notably, this is _not_ the case when these bubbles are located within a chain of bubbles (i.e. when the start node has any other incoming edges, and/or when the end node has any other outgoing edges). Because in that case there is no longer a valid chain from the end to the start.

This means that we can't just say "oh, identify the chain first, then find the bubble, etc." -- because this will fail if this cyclic bubble exists in a chain of bubbles. So we have to make a choice -- do we continue to allow cyclic bubbles (which means that their decomposition in isolated components may look like either of the two figures above), or do we reject them completely?

I guess we can continue to allow cyclic bubbles for now. This isn't really a _problem_ per se -- the fact that the decomposition is slightly inconsistent irks me, but it isn't really a bug (you could argue that either decomposition is meaningful -- in both cases we identify a bubble, anyway). My work on this project is already embarrassingly behind schedule as is.

Note that this also impacts cyclic frayed ropes (#242), when the connected end and start nodes have no non-pattern adjacencies. It doesn't impact cyclic chains since the "chain" from the end to the start of the cyclic chain is naturally a part of the cyclic chain anyway.

**Comment by fedarko** [comment]
Another thing worth noting is that, in a de Bruijn graph, a node with multiple loop edges to itself arguably constitutes a cyclic bulge. Should such cases be annotated as bulges? Maybe. There is not much benefit to doing so now, but if we start to do things like add sequence comparison functionality for bubbles/bulges maybe there will be a benefit.

**Comment by fedarko** [comment]
Test case:

```gfa
S	0	T
S	1	T
S	2	T
S	3	T
L	0	+	2	+	*
L	0	+	1	+	*
L	1	+	3	+	*
L	2	+	3	+	*
L	3	+	0	+	*
```

This is not great, IMO. If we disallow end-to-start cyclic bubbles explicitly, then we find the chain -> then find the bubble -> then find the cyclic chain -> then merge the chain into the cyclic chain, giving us just a cyclic chain pattern containing only a bubble pattern containing everything. This is not necessarily the _wrong_ way to decompose this, but this is the only case I'm aware of atm where you can have a pattern contain nothing but another pattern. I don't like it.

If we don't explicitly disallow end-to-start cyclic bubbles (current behavior), then the choice of what gets decomposed first is ambiguous - leading to jank like this:

<img width="1880" height="890" alt="Image" src="https://github.com/user-attachments/assets/0c1b034a-4c34-429f-b210-133c12ca05af" />

Not a _problem_ per se (this would be fixed by #268), but not ideal either. This is rare enough that I doubt it will even impact anyone, but it would be nice to make this consistent somehow. Maybe when we remove split nodes we add an extra step to see if any chains / cyclic chains are not useful afterwards...? I think that would fix this, although yuck, we might need to run it iteratively until things stop changing.

**Comment by fedarko** [comment]
Worth noting: this only impacts cyclic bubbles, as of writing. You can create an isolated cyclic frayed rope or bipartite, but since those are top-level patterns we don't have the risk of creating a cyclic chain including one of these:

<img width="1592" height="359" alt="Image" src="https://github.com/user-attachments/assets/3b8aa513-5b37-4a63-9d8f-af6eeecc4cf7" />

For dealing with cyclic bubbles, maybe a plan is

1. disallow cyclic bubble identification
2. disallow the identification of a pattern if any of its start node and end nodes share a parent

If step 2 is a pain then we can just implement this check for bubbles. But I think this is reasonable! We can just create two sets (all parent pattern IDs of starts and of ends) and if they intersect BEFORE we reify something into a pattern then we know we're in this kind of goofy situation
